# Generated by Django 4.1.3 on 2022-11-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Owner',
            new_name='User',
        ),
    ]
