# Generated by Django 4.1.3 on 2022-12-09 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_owner_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_deadline_missed',
        ),
    ]
